### ISSUE TITLE
Additional experimental settings

### ISSUE THREAD

**Issue by wykang** [MrtnMndt/OCDVAE_ContinualLearning#2]
I think if you provide other incremental learning settings such permuted MNIST, it will be very useful for many other researchers looking diverse benchmarking results.

**Comment by MrtnMndt** [comment]
Thank you for the interest in our paper. We will consider also adding permuted MNIST, although it isn’t our top priority right now as we would much rather scale up to natural images instead. I believe our dataloaders are fairly generic and If you would like to use permuted MNIST, I would appreciate it if you could try to implement it and do a pull-request.
