### ISSUE TITLE
"Does Out-of-Distribution Detection Require Generative Classifiers" implementation

### ISSUE THREAD

**Issue by alexrame** [MrtnMndt/OCDVAE_ContinualLearning#3]
Thank you for the really great work!
I would like to know whether you plan to release the code associated with the highly correlated paper: "Open Set Recognition Through Deep Neural Network Uncertainty:
Does Out-of-Distribution Detection Require Generative Classifiers?".
I guess that most of the code is already here, but I would be very interested in replicating the results and trying to improve them with new type of generation.
Thank you in advance

**Comment by MrtnMndt** [comment]
Thanks for the feedback :). The code for the related work you are referring to is also open source at: https://github.com/MrtnMndt/Deep_Openset_Recognition_through_Uncertainty 

I haven’t gotten around to writing a full Readme with usage instructions etc. yet and might do some refactoring, but it’s essentially already usable if you want to dig through the nuances yourself. I’ll have the usage instructions updated in about a week when I get back from the ICCV conference.

**Comment by alexrame** [comment]
So cool! Thank you, your work is really inspiring.
I'll let you know if I do not manage to handle it
